// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Friends.web.Models
{
    [Table("City")]
    public partial class City
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string Name { get; set; }
    }
}