// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiSample.Models
{
    [Table("Student")]
    public partial class Student
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Name { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string MobileNumber { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Gender { get; set; }
        public int? Age { get; set; }
    }
}